name: Setup .NET sample
description: Setup SDK, restore local tools, and restore solution dependencies.

inputs:
  global-json-file:
    description: Path to global.json.
    required: false
    default: global.json
  solution-path:
    description: Path to solution or solution filter.
    required: false
    default: DevSecOpsPipelineSample.slnx

runs:
  using: composite
  steps:
  - name: Setup .NET SDK
    uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
    with:
      global-json-file: ${{ inputs.global-json-file }}

  - name: Restore local tools
    shell: bash
    run: dotnet tool restore

  - name: Restore solution
    shell: bash
    env:
      SOLUTION_PATH: ${{ inputs.solution-path }}
    run: dotnet restore "$SOLUTION_PATH"
